version: '3.4'

services:
  aspnetcoreapp:
    container_name: app1
    image: mcr.microsoft.com/dotnet/sdk:5.0
    ports:
      - 5000:5000
    volumes:
      - ./:/app
      #- ./Https:/root/.aspnet/https/    #dotnet dev-certs https --clean && dotnet dev-certs https --trust
      #- ./DataProtection-Keys:/root/.aspnet/DataProtection-Keys
    working_dir: /app
    command: dotnet watch run 
    